identifier: cyber60_rev_e
name: zmk60 Rev E
type: mcu
arch: arm
features:
  - studio
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
supported:
  - adc
  - usb_device
  - ble
  - ieee802154
  - pwm
  - i2c
  - watchdog
